export const viewAllD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/advance-data-science-ai-program.png",
    title: "Advanced Data Science",
    title1: "& AI Program",
    tag: "Data science",
    para: [
      "250 hours of Interactive Learning",
      "12 Projects + 1 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
    link1: "/data-science-certification-courses",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/advance-ai-ml-for-tech-professionals.png",
    title: "Advance AI & ML Program",
    title1: "for Tech Professionals",
    tag: "Data science",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,05,000 + GST",
    ],
    link1: "/advance-ai-ml-certification",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-for-managers.png",
    title: "Data Science & AI ",
    title1: "For Managers",
    tag: "Data science",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,05,000 + GST",
    ],
    link1: "/data-science-ai-cert-for-managers-leaders",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-master-program.png",
    title: "Data Science & AI ",
    title1: "Master Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
    link1: "/data-science-ai-masters-program",
  },
  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-analytics.png",
    title: "Data Analytics",
    title1: "Program",
    tag: "Data science",
    para: [
      "180 hours of Interactive Learning",
      "8 Projects",
      "Course Fee : ₹ 75,000 + GST",
    ],
    link1: "/s2-data-analytics",
  },

  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/full-stack-developer-course.png",
    title: "Software Development",
    title1: "Master Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
    link1: "/fssd",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/dsa%26system.png",
    title: "Data Structures Algorithms ",
    title1: "And System Design",
    tag: "Full stack",
    para: [
      "200 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/dsa",
  },
  // {
  //   id: 8,
  //   img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/full-stack-web-development.png",
  //   title: "Full-Stack Web ",
  //   title1: "Development Program",
  //   tag: "Full stack",
  //   para: [
  //     "200 hours of Interactive Learning",
  //     "12 Projects + 2 Capstones",
  //     "Course Fee : ₹ 70,000 + GST",
  //   ],
  //   link1: "/fswd",
  // },
];

export const ForProgrammersD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/advance-data-science-ai-program.png",
    title: "Advanced Data Science",
    tag: "Data science",
    title1: "& AI Program",
    para: [
      "250 hours of Interactive Learning",
      "12 Projects + 1 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
    link1: "/data-science-certification-courses",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/full-stack-developer-course.png",
    title: "Software Development",
    tag: "Full stack",
    title1: "Master Program",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
    link1: "/fssd",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-for-managers.png",
    title: "Data Science & AI ",
    tag: "Data science",
    title1: "For Managers",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,05,000 + GST",
    ],
    link1: "/data-science-ai-cert-for-managers-leaders",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/advance-ai-ml-for-tech-professionals.png",
    title: "Advance AI & ML Program",
    tag: "Data science",
    title1: "for Tech Professionals",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,05,000 + GST",
    ],
    link1: "/advance-ai-ml-certification",
  },

  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-master-program.png",
    title: "Data Science & AI ",
    title1: "Master Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
    link1: "/data-science-ai-masters-program",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/dsa%26system.png",
    title: "Data Structures Algorithms",
    title1: "And System Design",
    tag: "Full stack",
    para: [
      "200 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/dsa",
  },
  // {
  //   id: 8,
  //   img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/full-stack-web-development.png",
  //   title: "Full-Stack Web ",
  //   title1: "Development Program",
  //   tag: "Full stack",
  //   para: [
  //     "200 hours of Interactive Learning",
  //     "12 Projects + 2 Capstones",
  //     "Course Fee : ₹ 70,000 + GST",
  //   ],
  //   link1: "/fswd",
  // },
];
export const ForNonProgrammerD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/advance-data-science-ai-program.png",
    title: "Advanced Data Science",
    title1: "& AI Program",
    tag: "Data science",
    para: [
      "250 hours of Interactive Learning",
      "12 Projects + 1 Capstones",
      "Course Fee : ₹ 95,000 + GST",
    ],
    link1: "/data-science-certification-courses",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/advance-ai-ml-for-tech-professionals.png",
    title: "Advance AI & ML Program",
    title1: "for Tech Professionals",
    tag: "Data science",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,05,000 + GST",
    ],
    link1: "/advance-ai-ml-certification",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-for-managers.png",
    title: "Data Science & AI ",
    title1: "For Managers",
    tag: "Data science",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,05,000 + GST",
    ],
    link1: "/data-science-ai-cert-for-managers-leaders",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-master-program.png",
    title: "Data Science & AI ",
    title1: "Master Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
    link1: "/data-science-ai-masters-program",
  },

  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-analytics.png",
    title: "Data Analytics",
    title1: "Program",
    tag: "Data science",
    para: [
      "180 hours of Interactive Learning",
      "8 Projects",
      "Course Fee : ₹ 75,000 + GST",
    ],
    link1: "/s2-data-analytics",
  },
];

export const JobGuaranteeD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/data-science-ai-master-program.png",
    title: "Data Science & AI ",
    title1: "Master Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,25,000 + GST",
    ],
    link1: "/data-science-ai-masters-program",
  },
];
export const StackD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/full-stack-developer-course.png",
    title: "Software Development",
    title1: "Master Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
    link1: "/fssd",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/dsa%26system.png",
    title: "Data Structures Algorithms",
    title1: "And System Design",
    tag: "Full stack",
    para: [
      "200 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/dsa",
  },
  // {
  //   id: 3,
  //   img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/course.learnbay.co/NImages/full-stack-web-development.png",
  //   title: "Full-Stack Web ",
  //   title1: "Development Program",
  //   tag: "Full stack",
  //   para: [
  //     "200 hours of Interactive Learning",
  //     "12 Projects + 2 Capstones",
  //     "Course Fee : ₹ 70,000 + GST",
  //   ],
  //   link1: "/fswd",
  // },
];
