export const viewAllD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/advance-data-science-ai-program.webp",
    title: "Advanced Data Science",
    title1: "& AI Program",
    tag: "Data science",
    para: [
      "250 hours of Interactive Learning",
      "12 Projects + 1 Capstones",
      "Course Fee : ₹ 90,000 + GST",
    ],
    link1: "/data-science-certification-courses",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/advance -ai-ml-for-tech-professionals.webp",
    title: "Advance AI & ML Program",
    title1: "for Tech Professionals",
    tag: "Data science",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,00,000 + GST",
    ],
    link1: "/advance-ai-ml-certification",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-for-managers.webp",
    title: "Data Science & AI ",
    title1: "For Managers",
    tag: "Data science",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,00,000 + GST",
    ],
    link1: "/data-science-ai-cert-for-managers-leaders",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-with-job-guarantee.webp",
    title: "Data Science & AI with ",
    title1: "100% Placement Assistance Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
    link1: "/job-guarantee-or-money-back-data-science-ai",
  },
  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/dsa&system.webp",
    title: "Data Analytics",
    title1: "Program",
    tag: "Data science",
    para: [
      "180 hours of Interactive Learning",
      "8 Projects",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/s2-data-analytics",
  },

  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/full-stack-developer-course.webp",
    title: "Full-Stack Software",
    title1: "Development Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
    link1: "/fssd",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/dsa&system.webp",
    title: "Data Structures Algorithms ",
    title1: "And System Design",
    tag: "Full stack",
    para: [
      "200 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/dsa",
  },
  {
    id: 8,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/full-stack-web-development.webp",
    title: "Full-Stack Web ",
    title1: "Development Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/fswd",
  },
];

export const ForProgrammersD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/advance-data-science-ai-program.webp",
    title: "Advanced Data Science",
    tag: "Data science",
    title1: "& AI Program",
    para: [
      "250 hours of Interactive Learning",
      "12 Projects + 1 Capstones",
      "Course Fee : ₹ 90,000 + GST",
    ],
    link1: "/data-science-certification-courses",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/full-stack-developer-course.webp",
    title: "Full-Stack Software",
    tag: "Full stack",
    title1: "Development Program",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
    link1: "/fssd",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-for-managers.webp",
    title: "Data Science & AI ",
    tag: "Data science",
    title1: "For Managers",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,00,000 + GST",
    ],
    link1: "/data-science-ai-cert-for-managers-leaders",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/advance -ai-ml-for-tech-professionals.webp",
    title: "Advance AI & ML Program",
    tag: "Data science",
    title1: "for Tech Professionals",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,00,000 + GST",
    ],
    link1: "/advance-ai-ml-certification",
  },

  {
    id: 6,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-with-job-guarantee.webp",
    title: "Data Science & AI with ",
    title1: "100% Placement Assistance Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
    link1: "/job-guarantee-or-money-back-data-science-ai",
  },
  {
    id: 7,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/dsa&system.webp",
    title: "Data Structures Algorithms",
    title1: "And System Design",
    tag: "Full stack",
    para: [
      "200 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/dsa",
  },
  {
    id: 8,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/full-stack-web-development.webp",
    title: "Full-Stack Web ",
    title1: "Development Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/fswd",
  },
];
export const ForNonProgrammerD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/advance-data-science-ai-program.webp",
    title: "Advanced Data Science",
    title1: "& AI Program",
    tag: "Data science",
    para: [
      "250 hours of Interactive Learning",
      "12 Projects + 1 Capstones",
      "Course Fee : ₹ 90,000 + GST",
    ],
    link1: "/data-science-certification-courses",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/advance -ai-ml-for-tech-professionals.webp",
    title: "Advance AI & ML Program",
    title1: "for Tech Professionals",
    tag: "Data science",
    para: [
      "350 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,00,000 + GST",
    ],
    link1: "/advance-ai-ml-certification",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-for-managers.webp",
    title: "Data Science & AI ",
    title1: "For Managers",
    tag: "Data science",
    para: [
      "400 hours of Interactive Learning",
      "15 Projects + 1 Capstones",
      "Course Fee : ₹ 1,00,000 + GST",
    ],
    link1: "/data-science-ai-cert-for-managers-leaders",
  },
  {
    id: 4,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-with-job-guarantee.webp",
    title: "Data Science & AI with ",
    title1: "100% Placement Assistance Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
    link1: "/job-guarantee-or-money-back-data-science-ai",
  },

  {
    id: 5,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/dsa&system.webp",
    title: "Data Analytics",
    title1: "Program",
    tag: "Data science",
    para: [
      "180 hours of Interactive Learning",
      "8 Projects",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/s2-data-analytics",
  },
];

export const JobGuaranteeD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/data-science-ai-with-job-guarantee.webp",
    title: "Data Science & AI with ",
    title1: "100% Placement Assistance Program",
    tag: "Data science",
    para: [
      "500 hours of Interactive Learning",
      "20 Projects + 3 Capstones",
      "Course Fee : ₹ 1,20,000 + GST",
    ],
    link1: "/job-guarantee-or-money-back-data-science-ai",
  },
];
export const StackD = [
  {
    id: 1,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/full-stack-developer-course.webp",
    title: "Full-Stack Software",
    title1: "Development Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 1,10,000 + GST",
    ],
    link1: "/fssd",
  },
  {
    id: 2,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/dsa&system.webp",
    title: "Data Structures Algorithms",
    title1: "And System Design",
    tag: "Full stack",
    para: [
      "200 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/dsa",
  },
  {
    id: 3,
    img: "https://learnbay-wb.s3.ap-south-1.amazonaws.com/main/full-stack-web-development.webp",
    title: "Full-Stack Web ",
    title1: "Development Program",
    tag: "Full stack",
    para: [
      "300 hours of Interactive Learning",
      "12 Projects + 2 Capstones",
      "Course Fee : ₹ 70,000 + GST",
    ],
    link1: "/fswd",
  },
];
